name: Automated Secret Detection Demo

on:
  workflow_dispatch:

jobs:
  detect_leak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Gitleaks Scan (Before Remediation)
        run: |
          cat << EOF > before.html
          <tr>
            <td>github-pat</td><td>e7bbf71</td><td>3</td><td>Sush541</td><td>.github/workflows/demotest.txt</td>
          </tr>
          <tr>
            <td>generic-api-key</td><td>e7bbf71</td><td>4</td><td>Sush541</td><td>.github/workflows/demotest.txt</td>
          </tr>
          EOF

  remediate_secret:
    needs: detect_leak
    runs-on: ubuntu-latest
    steps:
      - name: Remediate Leaks
        run: echo "Remediation logic here (actual remediation command)"
        continue-on-error: true

  detect_after_remediation:
    needs: remediate_secret
    runs-on: ubuntu-latest
    steps:
      - name: Run Gitleaks Scan (After Remediation)
        run: |
          cat << EOF > after.html
          <tr>
            <td>None</td><td>None</td><td>None</td><td>None</td><td>None</td>
          </tr>
          EOF

  send_email:
    needs: [detect_leak, detect_after_remediation]
    runs-on: ubuntu-latest
    steps:
      - name: Download before remediation (if using upload-artifact in previous jobs)
        run: cat before.html > /tmp/before.html
      - name: Download after remediation (if using upload-artifact in previous jobs)
        run: cat after.html > /tmp/after.html

      - name: Build HTML Email Body
        id: build_html
        run: |
          cat << EOF > email_body.html
          <html>
          <body>
          <h2>Gitleaks Detection Report</h2>
          <table border="1" cellpadding="5" cellspacing="0">
            <tr>
              <th>Rule ID</th>
              <th>Commit</th>
              <th>Line</th>
              <th>Author</th>
              <th>File</th>
            </tr>
            <tr><td colspan="5" align="center"><b>BEFORE REMEDIATION</b></td></tr>
          $(cat /tmp/before.html)
            <tr><td colspan="5" align="center"><b>AFTER REMEDIATION</b></td></tr>
          $(cat /tmp/after.html)
          </table>
          </body>
          </html>
          EOF

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.FROM_EMAIL }}
          subject: "Gitleaks scan results (Before & After Remediation)"
          html_body: ${{ steps.build_html.outputs.body || '' }}
        continue-on-error: true

      - name: Print HTML (debug)
        run: cat email_body.html
