name: Automated Secret Detection Demo

on:
  workflow_dispatch:

jobs:
  add_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add dummy secrets
        run: |
          echo 'AWS_SECRET_ACCESS_KEY=AKIA123FAKEDEMO123456' >> demotest.txt
          echo 'github_pat_ghp_DEMO123456789abcdef' >> demotest.txt
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add demotest.txt
          git commit -m "Add dummy secrets for demo"
          git push

  detect_leak:
    needs: add_secret
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Gitleaks scan
        uses: zricethezav/gitleaks-action@v2
        with:
          scan_args: detect --source . --report-format json --report-path gitleaks-report.json
        continue-on-error: true

      - name: Generate HTML report from Gitleaks JSON
        run: |
          cat > report.js << 'EOF'
          const fs = require('fs');
          let html = '<p>No leaks detected ✅</p>';

          if (fs.existsSync('gitleaks-report.json')) {
            const data = JSON.parse(fs.readFileSync('gitleaks-report.json', 'utf8'));
            let findings = [];

            // Support both flat and commit-based formats
            if (Array.isArray(data)) { // Flat array format
              findings = data;
            } else if (data.commits && Array.isArray(data.commits)) { // Gitleaks v8+ commit mode
              data.commits.forEach(commit => {
                if (commit && Array.isArray(commit.findings)) {
                  commit.findings.forEach(f => findings.push({
                    file: f.file || commit.file || '',
                    line: f.line || '',
                    secret: f.secret || f.match || '',
                    rule: f.rule || f.ruleID || '',
                  }));
                }
              });
            }
            if (findings.length > 0) {
              html = '<h2>Gitleaks detected secrets 🚨</h2>';
              html += '<table border=1><tr><th>File</th><th>Line</th><th>Secret</th><th>Rule</th></tr>';
              findings.forEach(d => {
                html += `<tr><td>${d.file}</td><td>${d.line}</td><td>${d.secret}</td><td>${d.rule}</td></tr>`;
              });
              html += '</table>';
            }
          }
          fs.writeFileSync('gitleaks-report.html', html);
          EOF
          node report.js

      - name: Cat generated HTML
        run: cat gitleaks-report.html

      - id: read_html
        name: Read HTML report for email
        run: |
          REPORT=$(cat gitleaks-report.html)
          echo "html_body<<EOF" >> $GITHUB_OUTPUT
          echo "$REPORT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send email with scan results
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Gitleaks Scan Results (BEFORE REMEDIATION) for ${{ github.repository }}"
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.FROM_EMAIL }}
          content_type: text/html
          body: ${{ steps.read_html.outputs.html_body }}

  remediate_secret:
    needs: detect_leak
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Remove dummy secrets
        run: |
          sed -i '/AWS_SECRET_ACCESS_KEY/d' demotest.txt
          sed -i '/github_pat_ghp_DEMO123456789abcdef/d' demotest.txt
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add demotest.txt
          git commit -m "Remove dummy secrets"
          git push

  detect_after_remediation:
    needs: remediate_secret
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Gitleaks scan
        uses: zricethezav/gitleaks-action@v2
        with:
          scan_args: detect --source . --report-format json --report-path gitleaks-report.json
        continue-on-error: true

      - name: Generate HTML report from Gitleaks JSON
        run: |
          cat > report.js << 'EOF'
          const fs = require('fs');
          let html = '<p>No leaks detected ✅</p>';

          if (fs.existsSync('gitleaks-report.json')) {
            const data = JSON.parse(fs.readFileSync('gitleaks-report.json', 'utf8'));
            let findings = [];

            if (Array.isArray(data)) {
              findings = data;
            } else if (data.commits && Array.isArray(data.commits)) {
              data.commits.forEach(commit => {
                if (commit && Array.isArray(commit.findings)) {
                  commit.findings.forEach(f => findings.push({
                    file: f.file || commit.file || '',
                    line: f.line || '',
                    secret: f.secret || f.match || '',
                    rule: f.rule || f.ruleID || '',
                  }));
                }
              });
            }
            if (findings.length > 0) {
              html = '<h2>Gitleaks detected secrets 🚨</h2>';
              html += '<table border=1><tr><th>File</th><th>Line</th><th>Secret</th><th>Rule</th></tr>';
              findings.forEach(d => {
                html += `<tr><td>${d.file}</td><td>${d.line}</td><td>${d.secret}</td><td>${d.rule}</td></tr>`;
              });
              html += '</table>';
            }
          }
          fs.writeFileSync('gitleaks-report.html', html);
          EOF
          node report.js

      - name: Cat generated HTML after remediation
        run: cat gitleaks-report.html

      - id: read_html_after
        name: Read HTML report after remediation
        run: |
          REPORT=$(cat gitleaks-report.html)
          echo "html_body<<EOF" >> $GITHUB_OUTPUT
          echo "$REPORT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send email with scan results after remediation
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Gitleaks Scan Results (AFTER REMEDIATION) for ${{ github.repository }}"
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.FROM_EMAIL }}
          content_type: text/html
          body: ${{ steps.read_html_after.outputs.html_body }}
