name: Automated Secret Detection Demo

on:
  workflow_dispatch:

jobs:
  detect_leak:
    runs-on: ubuntu-latest
    outputs:
      before_rows: ${{ steps.make_html.outputs.before_rows }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Before Table Rows
        id: make_html
        run: |
          echo "<tr><td>github-pat</td><td>e7bbf71</td><td>3</td><td>Sush541</td><td>.github/workflows/demotest.txt</td></tr>
<tr><td>generic-api-key</td><td>e7bbf71</td><td>4</td><td>Sush541</td><td>.github/workflows/demotest.txt</td></tr>" > before_rows.txt
          BEFORE_ROWS=$(cat before_rows.txt)
          echo "before_rows<<EOF" >> $GITHUB_OUTPUT
          echo "$BEFORE_ROWS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  remediate_secret:
    needs: detect_leak
    runs-on: ubuntu-latest
    steps:
      - name: Remediation
        run: echo "Remediation step"
        continue-on-error: true

  detect_after_remediation:
    needs: remediate_secret
    outputs:
      after_rows: ${{ steps.make_html.outputs.after_rows }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate After Table Rows
        id: make_html
        run: |
          echo "<tr><td>None</td><td>None</td><td>None</td><td>None</td><td>None</td></tr>" > after_rows.txt
          AFTER_ROWS=$(cat after_rows.txt)
          echo "after_rows<<EOF" >> $GITHUB_OUTPUT
          echo "$AFTER_ROWS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  send_email:
    needs: [detect_leak, detect_after_remediation]
    runs-on: ubuntu-latest
    steps:
      - name: Compose HTML Email
        id: email
        run: |
          cat << EOF > email_body.html
<html>
<body>
<h2>Gitleaks Detection Report</h2>
<table border="1" cellpadding="5" cellspacing="0">
  <tr>
    <th>Rule ID</th>
    <th>Commit</th>
    <th>Line</th>
    <th>Author</th>
    <th>File</th>
  </tr>
  <tr><td colspan="5" align="center"><b>BEFORE REMEDIATION</b></td></tr>
  ${BEFORE_ROWS}
  <tr><td colspan="5" align="center"><b>AFTER REMEDIATION</b></td></tr>
  ${AFTER_ROWS}
</table>
</body>
</html>
EOF
        env:
          BEFORE_ROWS: ${{ needs.detect_leak.outputs.before_rows }}
          AFTER_ROWS: ${{ needs.detect_after_remediation.outputs.after_rows }}
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.FROM_EMAIL }}
          subject: "Gitleaks scan results (Before & After Remediation)"
          html_body: ${{ steps.email.outputs.body || '' }}
        continue-on-error: true
      - name: Print HTML (debug)
        run: cat email_body.html
