name: Automated Secret Detection Demo

on:
  workflow_dispatch:

jobs:
  add_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Add Secret
        run: echo "Adding demo secret..."

  detect_leak:
    needs: add_secret
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run Gitleaks Scan
        run: echo "Running gitleaks..."

  remediate_secret:
    needs: detect_leak
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Remediate Secrets
        run: |
          echo "Remediating secrets..."
        continue-on-error: true

  send_email:
    needs: remediate_secret
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Gitleaks scan results"
          to: sushcadbury541@gmail.com
          from: sushmithamittapalli97@gmail.com
          body: "Scan and remediation run complete."
        continue-on-error: true

  detect_after_remediation:
    needs: remediate_secret
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Final Gitleaks Scan
        run: echo "Final scan after remediation..."
