name: Automated Secret Detection Demo

on:
  workflow_dispatch:

jobs:
  detect_leak:
    runs-on: ubuntu-latest
    steps:
      - name: Generate HTML Before Table
        run: |
          cat << EOF > before_rows.html
<tr><td>github-pat</td><td>e7bbf71</td><td>3</td><td>Sush541</td><td>.github/workflows/demotest.txt</td></tr>
<tr><td>generic-api-key</td><td>e7bbf71</td><td>4</td><td>Sush541</td><td>.github/workflows/demotest.txt</td></tr>
EOF
      - uses: actions/upload-artifact@v4
        with:
          name: before_rows
          path: before_rows.html

  remediate_secret:
    needs: detect_leak
    runs-on: ubuntu-latest
    steps:
      - name: Remediation step
        run: echo "Remediation logic."
        continue-on-error: true

  detect_after_remediation:
    needs: remediate_secret
    runs-on: ubuntu-latest
    steps:
      - name: Generate HTML After Table
        run: |
          cat << EOF > after_rows.html
<tr><td>None</td><td>None</td><td>None</td><td>None</td><td>None</td></tr>
EOF
      - uses: actions/upload-artifact@v4
        with:
          name: after_rows
          path: after_rows.html

  send_email:
    needs: [detect_leak, detect_after_remediation]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: before_rows
      - uses: actions/download-artifact@v4
        with:
          name: after_rows
      - name: Compose Email Body as Output
        id: compose
        run: |
          cat << EOF > email_body.html
<html>
<body>
<h2>Gitleaks Detection Report</h2>
<table border="1" cellpadding="5" cellspacing="0">
  <tr>
    <th>Rule ID</th>
    <th>Commit</th>
    <th>Line</th>
    <th>Author</th>
    <th>File</th>
  </tr>
  <tr><td colspan="5" align="center"><b>BEFORE REMEDIATION</b></td></tr>
  $(cat before_rows.html)
  <tr><td colspan="5" align="center"><b>AFTER REMEDIATION</b></td></tr>
  $(cat after_rows.html)
</table>
</body>
</html>
EOF
          body=$(cat email_body.html)
          echo "body<<EOHTML" >> $GITHUB_OUTPUT
          echo "$body" >> $GITHUB_OUTPUT
          echo "EOHTML" >> $GITHUB_OUTPUT

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.FROM_EMAIL }}
          subject: "Gitleaks scan results (Before & After Remediation)"
          html_body: ${{ steps.compose.outputs.body }}
        continue-on-error: true
      - name: Print HTML Body (debug)
        run: cat email_body.html
