name: Automated Secret Detection Demo

on:
  workflow_dispatch:

jobs:
  add_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

  detect_leak:
    needs: add_secret
    runs-on: ubuntu-latest
    steps:
      - name: Run Gitleaks Scan (Before Remediation)
        run: |
          echo "=== Gitleaks Scan BEFORE REMEDIATION ===" > before.txt
          # Replace the following with your actual gitleaks command
          echo "Sample: 2 secrets found" >> before.txt
      - name: Upload before remediation results
        uses: actions/upload-artifact@v4
        with:
          name: before
          path: before.txt

  remediate_secret:
    needs: detect_leak
    runs-on: ubuntu-latest
    steps:
      - name: Remediate Leaks
        run: echo "Remediation logic here (actual remediation command)"
        continue-on-error: true

  detect_after_remediation:
    needs: remediate_secret
    runs-on: ubuntu-latest
    steps:
      - name: Run Gitleaks Scan (After Remediation)
        run: |
          echo "=== Gitleaks Scan AFTER REMEDIATION ===" > after.txt
          # Replace the following with your actual gitleaks command
          echo "Sample: 0 secrets found" >> after.txt
      - name: Upload after remediation results
        uses: actions/upload-artifact@v4
        with:
          name: after
          path: after.txt

  send_email:
    needs: [detect_leak, detect_after_remediation]
    runs-on: ubuntu-latest
    steps:
      - name: Download before remediation artifact
        uses: actions/download-artifact@v4
        with:
          name: before
      - name: Download after remediation artifact
        uses: actions/download-artifact@v4
        with:
          name: after
      - name: Compose Email Body
        id: compose_body
        run: |
          echo "GITLEAKS SCAN REPORT" > email_body.txt
          echo "===================" >> email_body.txt
          cat before.txt >> email_body.txt
          echo "" >> email_body.txt
          cat after.txt >> email_body.txt
          echo "" >> email_body.txt
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.FROM_EMAIL }}
          subject: "Gitleaks scan results (Before & After Remediation)"
          body: |
            ${{ steps.compose_body.outputs.body || '' }}
        continue-on-error: true
      - name: Print Email Body (debug)
        run: cat email_body.txt
