name: Automated Secret Detection Demo

on:
  workflow_dispatch:

jobs:
  detect_leak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate HTML for BEFORE remediation
        run: |
          echo '<tr><td>github-pat</td><td>e7bbf71</td><td>3</td><td>Sush541</td><td>.github/workflows/demotest.txt</td></tr>' > before_rows.html
          echo '<tr><td>generic-api-key</td><td>e7bbf71</td><td>4</td><td>Sush541</td><td>.github/workflows/demotest.txt</td></tr>' >> before_rows.html
      - name: Save before_rows.html as artifact
        uses: actions/upload-artifact@v4
        with:
          name: before_rows
          path: before_rows.html

  remediate_secret:
    needs: detect_leak
    runs-on: ubuntu-latest
    steps:
      - name: Remediation step
        run: echo "Remediation logic (simulate here)."
        continue-on-error: true

  detect_after_remediation:
    needs: remediate_secret
    runs-on: ubuntu-latest
    steps:
      - name: Generate HTML for AFTER remediation
        run: |
          echo '<tr><td>None</td><td>None</td><td>None</td><td>None</td><td>None</td></tr>' > after_rows.html
      - name: Save after_rows.html as artifact
