name: Secret Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Gitleaks scan
        uses: zricethezav/gitleaks-action@v2
        with:
          scan_args: detect --report-format json --report-path gitleaks-report.json

      - name: Generate HTML report from Gitleaks JSON
        run: |
          cat > report.js << 'EOF'
          const fs = require('fs');
          let html = '<p>No leaks detected ✅</p>';
          if (fs.existsSync('gitleaks-report.json')) {
            const data = JSON.parse(fs.readFileSync('gitleaks-report.json', 'utf8'));
            if (Array.isArray(data) && data.length > 0) {
              html = '<table border=1><tr><th>File</th><th>Line</th><th>Secret</th><th>Rule</th></tr>';
              data.forEach(d => {
                html += `<tr><td>${d.file}</td><td>${d.line}</td><td>${d.secret}</td><td>${d.rule}</td></tr>`;
              });
              html += '</table>';
            }
          }
          fs.writeFileSync('gitleaks-report.html', html);
          EOF
          node report.js

      - name: Read HTML report for email
        id: read_html
        run: |
          REPORT=$(cat gitleaks-report.html)
          echo "html_body<<EOF" >> $GITHUB_OUTPUT
          echo "$REPORT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send email with scan results
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Gitleaks Scan Results for ${{ github.repository }}"
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.FROM_EMAIL }}
          content_type: text/html
          body: ${{ steps.read_html.outputs.html_body }}
